/* Mounted Riot Police — part book (keys: HORSE_KEYS in horse.ts). Canvas 36×34, hooves on
 * row 30. Dark bay police horse with white socks, hi-vis "POLICE" saddle cloth and a clear face
 * visor; rider in navy riot kit, visor up, magnificent moustache, long baton.
 * Leg poses are single legs on a 6×8 box (leg top = box column 2); horse.ts phases them into
 * the walk / gallop cycles. Keys H/h/d/W/K = near legs; far legs are re-keyed darker in code.
 * Do not reformat. */

export const HORSE_LEGS = `
== leg.plant 0,0
..HHh.
..HHh.
...Hh.
...Hh.
...Hh.
...Hh.
...WW.
..KKK.

== leg.fwd 0,0
..HHh..
..HHh..
...Hh..
...Hh..
....Hh.
....Hh.
....WW.
....KKK

== leg.back 0,0
..HHh.
..HHh.
..Hh..
..Hh..
.Hh...
.Hh...
.WW...
KKK...

== leg.lift 0,0
..HHh.
..HHh.
..Hhh.
..hHH.
.hHd..
.WW...
KK....
......

== leg.tuck 0,0
..HHh.
..HHhh
...hHH
..WWd.
.KK...
......
......
......

== leg.reach 0,0
..HHh..
..HHhh.
....HHh
.....Hh
.....WW
.....KK
.......
.......
`;

export const HORSE_PARTS = `
== shadow 6,28
....%%%%%%%%%%%%%%%%%....
.%%%%%%%%%%%%%%%%%%%%%%%.
%%%%%%%%%%%%%%%%%%%%%%%%%
.%%%%%%%%%%%%%%%%%%%%%%%.

# ---------------------------------------------------------------- SE horse
== horse.body 6,14
..hHGGGHh......HHh..
.hHGGGHHHhhhhhhHHHh.
hHGGGHHHHHHHHHHHHHHh
hHGGHHyYYYYYYYYyHHHh
hHHHHHyYYoYoYoYyHHHh
hHHHHHyYYYYYYYYyHHhd
dhHHHHyyyyyyyyyyHhhd
.dhhHHHHHHHHHHHHhhd.
..ddhhhhhhhhhhhhhd..
....ddd.......ddd...

== horse.head 18,5
.......dd....
......dHHd...
.....MHGHd...
....MMHGGHh..
...MMHHGyHHh.
..MMHHHHeVHHh
..MHHHHHHhVHH
.MMHHHH..hHHG
.MHHHH....hHH
MMHHHH....dKK
MHHHHH.....o.
MHHHH........

# Head tossed up (idle fidget / rear).
== horse.head.up 18,3
......dd.....
.....dHHd....
....MHGHd....
...MMHGGHh...
..MMHHGyHHhh.
..MHHHHHeVHHH
.MMHHHHHHhVHK
.MHHHHH...hKo
MMHHHHH......
MHHHHH.......
MHHHH........
MHHH.........
MHHH.........

# Head down (grazing nod / snort).
== horse.head.down 18,7
.............
.......dd....
......dHHd...
.....MHGHd...
....MMHGGHh..
...MMHHGyHHh.
..MMHHHHeVHH.
..MHHHHHHhVHh
.MMHHHH...hHH
.MHHHH.....hH
MMHHHH.....dK
MHHHHH......o

== tail 2,14
..MM
.MMm
MMm.
Mm..
Mm..
Mm..
mm..
m...

== tail.swish 1,14
...MM
..MMm
.MMm.
MMm..
Mm...
m....
.....
.....

== tail.fly 0,13
.....MM
..MMMMm
MMMMmm.
Mmm....
m......

# ---------------------------------------------------------------- SE rider
== rider.torso 11,9
.2444332..
3444443321
3yYYYYyy21
3yyyyyyy21
.oooogooo.

== rider.head 10,1
....3zzzz...
..334vwwVz..
.3344444zz2.
.3333333332.
.2233LeLLeL.
.2232LLLLLs.
.22123MMMMs.
..1123SMMS..
...11.sss...

== rider.head.hurt 10,1
....3zzzz...
..334vwwVz..
.3344444zz2.
.3333333332.
.2233eeLeeL.
.2232LLLLLs.
.22123MoMMs.
..1123SooS..
...11.sss...

== rider.leg 12,14
.33..
.332.
..32.
..32.
..nB.
.nBBb

# Long baton resting on the shoulder.
== rider.arm.rest 8,3
x.......
.x......
..x.....
...X....
....jJ..
...3jj..
..3443..
.34443..
.3443...

# Baton cocked high behind.
== rider.arm.up 4,0
x.........
.x........
..x.......
...XjJ....
....jj....
.....43...
.....432..
.....4432.
......344.
.....3444.
.....3443.

== rider.arm.over 9,1
........jJXXxxx
........jjX....
.......443.....
......443......
.....443.......
....3443.......
...3443........
..3443.........

== smear 6,0
.....vVVVVv......
...vV......VVv...
..v...........Vv.
.v...............
v................

# Strike: arm swept down the near side, baton chopping low past the shoulder of the horse.
== rider.arm.strike 9,9
.344...............
34443..............
.34443.............
..3443.............
...3443............
....344jJ..........
.....33jjXX........
..........XXx......
............xxx....
..............xx...

# ---------------------------------------------------------------- rear-up (deploy) — whole horse
== horse.rear 6,1
...................dd.....
..................dHHd....
.................MHGHd....
................MMHGGHh...
...............MMHHGyHHh..
..............MMHHHHeVHHh.
.............MMHHHHHHhVHHh
............MMHHHHH..hHHKo
...........MMHHHHHH.......
..........MHHHHHHHHh......
.........hHHHHHHHHHh......
........hHGGHHHHHHHHh.....
.......hHGGHHHHHHHHHh.....
......hHGGHHyYYYYHHHh.....
.....hHGHHHyYoYoyHHHh.....
.....hHHHHHyYYYYyHHhd.....
....hHHHHHHyyyyyHHhd......
....hHHHHHHHHHHHHhd.......
...hHHHHHHHHHHHhhd........
..MhHHHHHHHHhhdd..........
.MMhHHHHHHHhd.............
.MMhHHHHHHhd..............
MMm.hHHHHHd...............
Mm..hHHhHHd...............
Mm...hHh.Hh...............
m....Hh..Hh...............
.....Hh...Hh..............
....Hh....Hh..............
....WW....WW..............
...KKK...KKK..............

== rear.legs.front 0,0
.HHh....
..HHhh..
....hHH.
...WWHd.
..KK....

== rear.legs.front2 0,0
..HHh...
..HHhh..
...HHh..
...hHH..
..WWd...
..KK....

# ---------------------------------------------------------------- rider falling / lying
== rider.tumble 0,0
....3zzzz...
..334vwwVz..
.3344444zz2.
.2233eeLee..
..2123MoMs..
..3yYYYYy...
.34yyyyyy3..
.3333333333.
..nB....nB..
..bb....bb..

== rider.lie 2,21
..3zzz................
.334vwz..........bb...
3344444z.2444...3nBb..
3333eLe.344443333Bb...
2233MMs.3yYYyy3322....
.22.SSs.3yyyyy222.....
.........jJ...........

== rider.lie.flat 2,21
......................
..3zzz...........b....
.334vwz..2444...3nBb..
3344444.344443333Bb...
2233MMs.3yYYyy3322....
.22.SSs.3yyyyy222.....
.........jJ...........

== rider.shadow 2,26
...%%%%%%%%%%%%%%%....
.%%%%%%%%%%%%%%%%%%%%.
...%%%%%%%%%%%%%%%....

# ---------------------------------------------------------------- NE
== horse.body.ne 6,14
..hHH......hGGGHh...
.hHHHhhhhhhGGGHHHh..
hHHHHHHHHHHHGGGHHHh.
hHHyYYYYYYYYyHGGHHh.
hHHyYoYoYoYYyHHHHHh.
dhHyYYYYYYYYyHHHHHh.
dhhyyyyyyyyyyHHHHhd.
.dhhHHHHHHHHHHHHhhd.
..dhhhhhhhhhhhhhdd..
...ddd.......ddd....

== horse.head.ne 18,5
.....dd.dd...
....dHHdHHd..
....dHHHHHd..
...MMHGHHh...
..MMMHHHHh...
..MMHHHHh....
.MMHHHHh.....
.MHHHHh......
MMHHHH.......
MHHHH........
MHHH.........

== tail.ne 3,16
.MM..
MMMm.
MMm..
.Mm..
.Mm..
.mm..
..m..

== rider.torso.ne 11,9
.2333322..
3444433321
3YYYYYYyy1
3yoyoyoyy1
.oooooooo.

== rider.head.ne 10,1
....3444....
..33444443..
.3344444432.
.3344443332z
.333333322zz
.233333222z.
.222222221..
..2222221...
...11111....

== rider.leg.ne 17,14
.33.
233.
23..
23..
Bn..
bBBn

== rider.arm.ne.rest 18,2
.......x
......x.
.....x..
....X...
..Jj....
..jj3...
..3443..
..34443.
...3443.

== rider.arm.ne.up 20,0
.........x
........x.
.......x..
....JjX...
....jj....
...34.....
..234.....
.2344.....
.443......
.4443.....
.3443.....

== rider.arm.ne.strike 18,7
...............x
..............xX
.............xX.
...........JjX..
..........jj....
.........34.....
.443....344.....
44443.3443......
.344444.........
..344...........
`;
