// Hand-drawn Stockholm sprites (keys o d m l h = figure ramp, see props.ts `figure`).
// Prettier-ignored grids.

/** Tre Kronor: the three gilded crowns on Stadshuset's spire (two over one, on the rod). */
export const THREE_CROWNS = `
h.h.h.h.h.h
hlhlh.hlhlh
lllll.lllll
mmmmm.mmmmm
..d..o..d..
...h.h.h...
...hlhlh...
...lllll...
...mmmmm...
.....o.....
.....o.....
`;
