/**
 * PRAGUE pixel grids (E3 Central). Facade modules use the keys of bld/modules.grid.ts; prop
 * grids the keys of props.grid.ts. Hand-aligned — never reflow (Prettier-ignored).
 */

// ------------------------------------------------------------------------- facade modules --

/** Baroque window with "ears", a segmental head and a keystone. */
export const PRG_WIN = `
...UU...
.UUUUUU.
UTkkkkTU
.TkGgkT.
.TffffT.
.TkgGkT.
.TGgkkT.
.TkggkT.
.UUUUUU.
..t..t..
`;

/** Piano-nobile window under a curved (segmental) pediment. */
export const PRG_WIN_TALL = `
..UUUU..
.UttttU.
UUUUUUUU
.TkkkkT.
.TkGgkT.
.TffffT.
.TkgGkT.
.TGgkkT.
.TkggkT.
.UUUUUU.
`;

/** Small Gothic / Renaissance window with a stone frame and a mullion. */
export const PRG_WIN_SMALL = `
........
..TTTTt.
..TkfGT.
..TkfkT.
..TgfkT.
..TkfgT.
..UUUUU.
........
........
........
`;

/** Window-box of geraniums (Prague sills are full of them). */
export const PRG_FLOWERBOX = `
........
........
........
........
........
........
........
.PpPpPp.
.ssssss.
........
`;

/** Arcade bay (podloubí): round arch on piers, deep shade, a lit shop glimpsed inside. */
export const PRG_ARCADE = `
TTTTTTTT
TtUUUUtT
TUxxxxUT
TxxxxxxT
TxxkGxxT
TxxkkxxT
TxxggxxT
TxxDDxxT
TxxDDxxT
tttttttt
`;

/** Street door under a painted house sign (domovní znamení). */
export const PRG_DOOR = `
..nyyn..
..nyNn..
.UUUUUU.
.TdDDdT.
.TDdDDT.
.TDDhDT.
.TDdDDT.
.TDDDDT.
.TDdDDT.
tttttttt
`;

/** Ground-floor window with a wrought grille. */
export const PRG_GWIN = `
........
.UUUUUU.
.TkkkkT.
.IiIiIT.
.TiGiGT.
.IiIiIT.
.TigigT.
.UUUUUU.
........
........
`;

/** Souvenir / Bohemian-crystal shop (2 bays): stone frame, sign, bright goods in the window. */
export const PRG_SHOP = `
TTTTTTTTTTTTTTTT
TnnnnnnnnnnnnnnT
TnNnNNnNnNNnNnnT
TfkcCkPkcCkfDDfT
TfCkkPkCkkPfDdfT
TfkPcCkkPcCfDhfT
TfcCkkPckkkfDDfT
TfffffffffffDDfT
TsssssssssssDDfT
tttttttttttttttt
`;

/** Pivnice (beer hall): dark wood, gilt sign, an awning and lit leaded panes. */
export const PRG_PUB = `
nnnnnnnnnnnnnnnn
nNnNNnNnnNNnNnNn
aaAAaaAAaaAAaaAA
.a..A..a..A..a..
DkGgkkDkkgGkDDdD
DkgGkkDkGgkkDDhD
DkkgkkDkkkgkDDdD
DDDDDDDDDDDDDDdD
DdDdDdDdDdDdDDdD
tttttttttttttttt
`;

/** Czech flag hung from a window (1 white, 2 red, 3 blue wedge). */
export const PRG_FLAG = `
........
........
........
........
........
........
.x......
.311111.
.332222.
.322222.
........
`;

// ---------------------------------------------------------------------------------- props --

/** Old Town lamp: dark post, big hexagonal lantern under a pointed crown. */
export const LAMP_PRAGUE = `
.....A.....
.....M.....
....MMm....
...MMMmm...
..MMMMMmm..
...MLFLm...
...MLLFm...
...MLLLm...
...MLLLm...
..MMMMMmm..
....MMm....
....M.m....
.....M.....
....MMm....
....AAA....
....MMm....
....MMm....
....MMm....
....MMm....
....MMm....
....MMm....
....MMm....
....AMm....
....MMm....
....MMm....
....MMm....
...MMMmm...
...AAAAA...
..MMMMmmm..
..MmMmMmm..
.MMMMMmmmm.
`;

/** Metro sign: the arrow-M on line A green. */
export const METRO_PRAGUE = `
hhhhhhhhh
hwhhhhhwh
hwwhhhwwh
hwhwhwhwh
hwhhwhhwh
hwhwwwhwh
hhhhwhhhh
GGGGGGGGG
....Mm...
....Mm...
....Mm...
....Mm...
....Mm...
....Mm...
....Mm...
....Mm...
....Mm...
....Mm...
....Mm...
....Mm...
...MMmm..
`;

/** Old Town bollard: dark cast iron with a ball top. */
export const BOLLARD_PRAGUE = `
.Mm.
MMmm
.Mm.
.Mm.
MMmm
.Mm.
.Mm.
MMmm
`;

/** Charles-Bridge style baroque saint (sandstone blackened with age) on a pedestal. */
export const STATUE_PRAGUE = `
..y.y......
...yy......
...Qq......
..qQQqq....
.qQQQQqQ...
.Q.QQQqq...
...QQQq.q..
...QQQq....
..qQQQqq...
..QQQQqq...
.qQQQQQqq..
.WWWWWWWWS.
.TTTTTTTSs.
..TTTTTSs..
..TtTTTSs..
..TTTTTSs..
..TTTTTSs..
.TTTTTTTSs.
WWWWWWWWWSs
TTTTTTTTTSs
`;

/** St Wenceslas on horseback with his lance and pennant. */
export const EQUESTRIAN_PRAGUE = `
..........c.........
..........cC........
..........y.........
.......Qq.y.........
.......QQ.y.........
......qQQqy.........
..Qq..QQQqy.........
.QQQq.qQqq..........
QQqQQqQQqqqqqqq.....
qq.qQQQQQQQQqqqq....
....qQQQQQQQQQqqqq..
.....QQQqqqqqqqq.qq.
.....Qq.Qq...qQ.qq..
.....Qq..Qq..Q..q...
....Qq...Qq.Qq..q...
....q.....q.q....q..
.WWWWWWWWWWWWWWWWWWS
.TTTTTTTTTTTTTTTTTSs
.TTtTTTTTTTTTTTTTTSs
.TTTTTTTTTTTTTTTTTSs
.TTTTTTTTTTTTTTtTTSs
.TTTTTTTTTTTTTTTTTSs
WWWWWWWWWWWWWWWWWWWS
TTTTTTTTTTTTTTTTTTSs
`;
