// Hand-drawn Rome landmark figures (keys o d m l h = material ramp, see props.ts figure()).

/** Trevi: Oceanus striding on his shell chariot, a winged sea-horse rearing, a triton leading. */
export const OCEANUS = `
...........oo...........
..........ohlo..........
..........ohlo..........
.........oohloo.........
........ohhllmmo........
.......ohlhllmmmo.......
.......ol.ohlmo.mo......
..........ohlmmo........
.........ohlollmo.......
.........ohlo.olmo......
..oo....ohlo...olmo.....
.ohho..ooooooooooooo....
ohhlmoohhhllllllllmmo...
.ohlmmohllllllllmmmmdo..
..olmmmoollllllmmmmddo..
.ohollmo.ooollmmmmdddo..
ohlo.olo....ooooooooo...
olo...oo................
oo......................
`;

/** Vittoriano quadriga: four horses abreast, winged Victory in the chariot (facing SW). */
export const QUADRIGA = `
..................o....o..
.................oho..oho.
.................ohho.ohho
..................ohhohho.
...................ohlho..
...................ohlmo..
..........oo......oohlmo..
....oo...ohho....ohhllmo..
...ohho.ohhlo...ohllllmo..
..ohhlo.ohlo...oooollmmo..
.ohllo.ohllo..ohhllllmmo..
ohlo.oohllo..ohllllllmmdo.
olo.ohhhlo..ohlllllmmmddo.
.o.ohhllooooohlllllmmmddo.
..ohhllllllllllllllmmmddo.
..ohllllllllllllllmmmddo..
...olllmmmmllllmmmmmddo...
...olmo.olmo.olmo.olddo...
...olmo.olmo.olmo.oddo....
..ohlmo.olmo.ohlmo.ooo....
..oooo..oooo.oooo.........
`;

/** Vittorio Emanuele II on horseback (gilt bronze), facing SW. */
export const EQUESTRIAN = `
........oo.........
.......ohlo........
.......ohlo........
......oohlmoo......
..oo..ohllmmo......
.ohhoohhllmmmo.....
ohhlhohhlllmmo.....
olohhhllllmmmooooo.
.o.ohhllllllmmmmmdo
...ohllllllmmmmmddo
....olllmmmmmmmddo.
....olmo.oo..olmdo.
....olmo.....olmo..
...ohlmo....ohlmo..
...oooo.....oooo...
`;

/** A Trevi allegory in a side niche (Abundance / Health), standing. */
export const NICHE_FIGURE = `
.oo.
ohlo
.oo.
ohlo
ohmo
ohmo
olmo
olmo
oooo
`;
