/**
 * Hand-authored facade modules (M3a). Each cell is one bay × one storey (8×10 px) or a 2-bay
 * shopfront (16×10), drawn *unsheared* in face space — the rasterizer shears them onto the iso
 * face. Openings and overlays are separate so balconies, blinds, plants, laundry, banners and
 * peeking residents combine freely.
 *
 * Keys (resolved per building / per window by the facade painter):
 *   .  wall (transparent)        w  wall shadow             W  wall highlight
 *   T  trim (stone surround)     t  trim shadow             U  trim highlight
 *   g  glass                     G  glass reflection        k  glass deep / interior
 *   f  window frame              F  frame shadow
 *   S  shutter / blind           s  shutter shadow
 *   I  iron highlight            i  iron                    x  ink
 *   D  door                      d  door shadow             h  brass handle / knocker
 *   a  awning                    A  awning stripe           n  sign board   N  sign letters
 *   m  metal                     M  metal highlight         c  curtain / cloth   C  cloth 2
 *   p  leaves                    P  flowers                 e  skin   H  hair   r  red   y  yellow
 */

// City modules (doors, windows, balconies, shopfronts) live in ../cities/<city>.grid.ts.

// ----------------------------------------------------------------------- Shared overlays ----

/** Flower pots on a balcony / sill. */
export const FLOWERS = `
........
........
........
........
.pPp.Pp.
pPpp.pPp
........
........
........
........
`;

/** Laundry hung over the balcony rail. */
export const LAUNDRY = `
........
........
........
........
........
xxxxxxxx
.cc.CC..
.cc.CC.c
.c..C...
........
`;

/** Resident peeking out (head and shoulders in the opening). */
export const PEEK = `
........
........
........
...HH...
...ee...
..cHec..
..cccc..
........
........
........
`;

/** Window air-conditioning box on the wall beside a window (Madrid). */
export const AC_UNIT = `
........
........
........
........
........
........
.....mMM
.....mxm
.....mmm
......x.
`;

/** Protest bed-sheet banner hanging from the balcony ("NO"). Spans the storey below. */
export const BANNER_NO = `
........
........
........
........
........
........
x......x
cccccccc
crcccrcc
crrcrcrc
crcrrcrc
crccrcrc
cccccccc
`;

/** Flag hung from a balcony (stripes = c / C / c). */
export const BALCONY_FLAG = `
........
........
........
........
........
........
.x......
.cccccc.
.CCCCCC.
.CCCCCC.
.cccccc.
`;

/** Satellite dish bolted to the wall. */
export const SAT_DISH = `
........
........
........
......MM
.....MmM
.....mMx
......x.
........
........
........
`;

/** Drainpipe hopper head + pipe segment (column 0 = pipe). */
export const PIPE_HEAD = `
mm
mx
m.
`;
